### Get all
GET http://localhost:3001/transactions

###

POST http://localhost:3001/transactions
Content-Type: application/json

{
    "description":"Salary",
    "amount":3000,
    "type":"Income",
    "category":"Job"
}

###

GET http://localhost:3001/transactions